name: Cortex Ingestion

on:
  push:
    branches: ["main"]
    paths:
      - .cortex/**
      - docs/**

jobs:
  cortex-ingest:
    uses: loash-industries/workflows/.github/workflows/js-cortex-ingest.yaml@v0.4.3
    if: github.ref == 'refs/heads/main'
    with:
      cortex_api_url: "https://cortex-relay-dev-api.trinary.exchange"
      npm_private_registry_url: "https://npm.pkg.github.com/"
      npm_client: npm
    secrets:
      CORTEX_INGEST_TOKEN: ${{ secrets.CORTEX_INGEST_TOKEN }}
      GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
